### ISSUE TITLE
[Documentos] Melhorar o Roadmap

### ISSUE THREAD

**Issue by antoniotoineto** [fga-eps-mds/2023-1-Dnit-DOC#72]
**Descrição**
Melhorar o Roadmap para ficar mais claro e objetivo para o cliente

**Informações adicionais**

***Checklist***
A issue: 
- [x] Possui título; 
- [x] Possui descrição; 
- [x] Possui pelo menos um assinante responsável; 
- [x] Possui labels cabiveis.  
- [x] Foi associada ao projeto(no github);
